### ISSUE TITLE
is it possible to running like realtime?

### ISSUE THREAD

**Issue by liquidzym** [Jonathhhan/ofxStableDiffusion#1]
sorry for asking,is it possible to running as realtime with [SDXL-Turbo](https://huggingface.co/stabilityai/sdxl-turbo)?

**Comment by Jonathhhan** [comment]
@liquidzym no realtime is not possible, but sd-turbo and sdxl-turbo do work and they are quite fast...

**Comment by liquidzym** [comment]
thank you,i just thought this might be working directly with turbo model nearly realtime instead of the Stream diffusion pipeline

**Comment by Jonathhhan** [comment]
@liquidzym it is nearly realtime, I guess with GPU it takes around one second.

**Comment by liquidzym** [comment]
i just did some testing during the weekend, still a bit slower compared with  Stream diffusion, i'm not sure which step i did wrong, i did some testing using turbo lcm and  ‎SDXL  model as well, both i have to setup steps as 4 otherwise the images not so good, under the img2img ,4090rtx

**Comment by Jonathhhan** [comment]
I guess, stream diffusions pipeline is better optimized. Would be nice, if it is possible to implement that pipeline in stable-diffusion.cpp...

**Comment by liquidzym** [comment]
yeah,the stream diffusions got some optimized,that would be really nice if can bring it to stable-diffusion.cpp
