### ISSUE TITLE
updated issue

### ISSUE THREAD

**Issue by liquidzym** [Jonathhhan/ofxStableDiffusion#2]
sorry it's not actual issue, those two methods needs to change
C2660 'new_sd_ctx': function does not accept 14 arguments 
“txt2img”:  function does not accept 13 arguments
after i recomplied the stable-diffusion.cpp recently

**Comment by Jonathhhan** [comment]
@liquidzym yes, i need to update the addon soon.

**Comment by liquidzym** [comment]
ok,thank you!

**Comment by Jonathhhan** [comment]
@liquidzym just updated the addon.

**Comment by liquidzym** [comment]
great,thank you so much
