### ISSUE TITLE
the img2img method need update it again

### ISSUE THREAD

**Issue by liquidzym** [Jonathhhan/ofxStableDiffusion#5]
truly sorry,me again，i just did recomplied the new SD c++ libs under the win11 with cuda backend, but it seems the img2img method needs to be updates ,needs to be 18 arguments,thank you!

**Comment by Jonathhhan** [comment]
@liquidzym no problem. not really sure, but I guess I already updated it.

**Comment by liquidzym** [comment]
the newest one need 18 arguments, the current only 13 arguments😂

**Comment by Jonathhhan** [comment]
I made quite a big update. Made an ofxStableDiffusion class (but you can still use the API directly, like before). Hope it works well.

**Comment by liquidzym** [comment]
![QQ截图20240517160755](https://github.com/Jonathhhan/ofxStableDiffusion/assets/51957/77e01292-9cd3-48ed-8fd4-49f6c58160b0)
super! thank you so much,work like a charm!
