### ISSUE TITLE
can you updated against to the last stable-diffusion.cpp

### ISSUE THREAD

**Issue by liquidzym** [Jonathhhan/ofxStableDiffusion#7]
sorry me again😂，is there any chance can you updated  src against to the last stable-diffusion.cpp
thank you so much for the help

**Comment by Jonathhhan** [comment]
@liquidzym feel free to open a PR. I will update it eventually, but not for every stable-diffusion.cpp commit.

**Comment by liquidzym** [comment]
ok,i'll send PR later on, thank you

**Comment by Jonathhhan** [comment]
@liquidzym I guess basically you just need to add the new arguments(and replace the lib, of course)...
